INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Magasin, Entrepot(grossiste, importateur et exportateur)', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Boutique/ Shop', '33237');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Kiosque, étalage', '33237');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Dépot pharmacetique', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Dépot des boissons et eauminerale', '44316');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Dépots des ciments,café,cacao,quinquina…', '44316');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Dépots des produits manifacturés', '66474');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Dépots des produits vivriere y compris poissons,huille de palme,canne à sucre…', '22158');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Dépôt diverses(SOZAPLAST, SOULIER)', '33237');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Dépot des braises', '22158');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Dépôt des planches : Bois rouge', '33237');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Dépôt des planches : Bois blanc', '22156');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Dépôt produits usagers(friperie) : Moyen', '332370');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Dépôt produits usagers(friperie) : Petit', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Contenaire autour du marché', '55395');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Pharmacies : Pharmacie', '33237');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Pharmacies : Officine pharmaceutique', '22158');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Pharmacies : Pharmacopée traditionnelle,agro-pastoal', '33237');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Quincaillerie', '33237');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Mitrailles', '33237');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Papeterie', '33237');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Librairie', '33237');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('pièces de rechange véhicule', '44316');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('piéces de rechange motos', '22158');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('piéces de rechange vélos', '11079');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Supers marchés', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Alimentation ordinaire', '44316');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Maison de vente des fromages', '22158');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Polycliniques', '197659');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Cliniques medicales et /ou vétérinaire', '177264');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Centre hospitalier, Centre Medical,Centre de santé,Medecine privée(FONGANGS, SIBO, ALOE,…)', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Dispensaires modernr et/ou tradiditionnel,poste de santé', '44316');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Laboratoire médical', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Lunetterie', '33237');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Dentisterie et/ou ophtalmologie…', '22158');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Ecoles privées', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Chambre froide', '77553');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Comptoires des matières présieuses', '221580');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Hotel : Cinq étoiles', '664740');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Hotel : Quatre étoiles', '553950');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Hotel : Trois étoiles', '443160');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Hotel : Deux étoiles', '332370');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Hotel : Une étoile', '221580');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Hotel : Sans étoile ou non classée', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Hotel : Loge,Guest house,Motel…', '88632');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Hotel : Centre accueil', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Salle de cinema', '22158');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Salle de massage', '44316');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Sauna', '44316');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('salle polyvalente', '221580');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Bars et/ou Nganda', '66474');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('buvettes', '31021.2');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Boite de nuit', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Casinos', '88632');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Salle de sport', '22158');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Salle de jeux', '22158');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Restaurant 4 fourchettes', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Restaurant 3 fourchettes', '33237');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Restaurant 2 fourchettes', '33237');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Restaurant 1 fourchette', '17726');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Restaurants sans fourchette(non)', '17726');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Cafétéria', '17726');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Charcuterie/fromagerie', '33237');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Poulailler', '33237');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Maison installation antenne cellulaire', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Maison de parienage', '221580');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Maison de decor, location des instruments, tentes, chaises…', '66474');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Revendeurs de cartes prépayées et charge téléphones', '11079');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Maisons des chaines numeriques', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Boucherie', '22158');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Bijouterie', '55395');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Maison de vente des bijoux en or,perles,diaments…', '44316');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Maison de vente des bijoux ordinaires', '22158');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Maison dachat et vente des matières', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Maison de vente peinture', '44316');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Maison délevage', '44316');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Agence en douane', '221580');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Maison de transfert argent : Moyenne dans des kiosques/Orange', '31021.2');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Maison de transfert argent : Petite sous parasol(Orangemoney,airtel)', '17726');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Maison de transfert argent : Agence de transfert', '221580');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Maison de transfert argent: Initution Micro finance', '221580');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Agence de voyage Lacustre', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Agence de voyage Routier', '55395');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Agence de voyage aérienne', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Compagnie de voyage aérienne', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Agence de fret aerienne et maritime', '221580');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Agence immobilière', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Cabinet juridiciaire', '88632');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Cabinet avocat', '88632');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Cabinet expertise comptable', '88632');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Bureau etude/consultance', '88632');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Commission et courtage', '88632');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Entreprise de construiction', '221580');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Bureau architecture et enginee', '221580');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Station service', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Garage', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Atélier de contrôle technique', '55395');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Atélier de reparation moto', '17726.4');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Cyber', '17726.4');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Maison de la nouvelle technologies', '17726.4');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Secrétariat public : cyber cafe', '17726.4');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Activités de reparation', '17726.4');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Réparateur(Radio,télévision,montre,téléphone…)', '17726');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Charge téléphone', '17726');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Activité de nettoyage : Nettoyage de véhicule et moto', '22158');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Activité de nettoyage : Blanchisseriz lavage en sec', '66474');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Laboratoire photos', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Studio photo', '22158');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Studio enregistrement', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Salon de coiffure homme,dame et mixte : Salon VIP', '66474');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Salon de coiffure homme,dame et mixte: Ordinaire', '22158');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Ateliers de couture', '22158');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Codonnerie', '33237');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Codonnerie : Fabrications chaussures', '66474');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Codonnerie : Réparation chaussures', '22158');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Ateliers,métalique,ajustage et soudure', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Aateliers de borsge et ajustage', '110.79');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Atelier de fabrication de marmites', '22158');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Atelier de fabrication des males', '44316');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Chantier Navale: Artisanal (pirogue)', '33237');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Ateliers de menuiserie : Fabrication des divants(salon garnis)', '77553');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Ateliers de menuiserie : Pompe funebre', '33237');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Ateliers de menuiserie : Fabrication des meubles non garnis', '33237');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Entreprise de gadinnage : société internationale', '443160');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Entreprise de gadinnage : Société nationale', '295440');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Entreprise de gadinnage : Société locale', '147720');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Société', '221580');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Maison de change', '221580');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Maison edition et videothèque', '22580');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Chaines radio et télévision privée : Radio', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Chaines radio et télévision privée : télévision', '221.58');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Chaines radio et télévision privée : Radio et  télévision', '332370');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Maison de vente de pain', '22158');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Maison de vente eau minérale', '22158');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Appartement', '110790');
INSERT INTO ttaxe_categorie (designation, prix_categorie) VALUES ('Centre de formation(informatique,langue,culinaire,métiers confondus)', '22158');